### ISSUE TITLE
Handy support for user identification, and track the start and end of a session

### ISSUE THREAD

**Issue by jvanecek** [ba-st/Willow-Mixpanel#10]
Would be nice to reify somehow the use case of identifying a user and store some information of them (using the #[identify](https://developer.mixpanel.com/docs/javascript-full-api-reference#mixpanelidentify) and #[set_once](https://developer.mixpanel.com/docs/javascript-full-api-reference#mixpanelpeopleset_once)), as well as a handy way to track the start and end of a session, since Mixpanel already identifies by default this events as $session_start and $session_end

**Comment by gcotelli** [comment]
Fixed by #11
